Added react-hook-form to the BazaWiedzy
bajton/bajton pull request #43
Opened 2023-06-06 12:12 UTC by Aruturuu

### **_Form Framework Council (FFC)_ decided on using _react-hook-form_.**

There were two competitors consisting of _**Formik**_ and _**react-hook-form**_.

Janitor decided to formalize a quick summary explaining our choice.
- Some members of the council tried both frameworks and found _**react-hook-form**_ to be easier to use. This may be because of simplicity of said framework, as it is much more ligthweight than _**Formik**_.
- The _**react-hook-form**_ displays better performance regarding load times and amount of re-renders.
- It also has slightly more stars on github with comparable amount of projects using it, it is not a significant argument.

2023-06-06 14:01 UTC, 0ZeroFive5 requested changes
-The version of react-hook-form is not pinned but set to 7.44.3 or later which might break something later on and is a possible dependency chain vulnerability, pin the version to the current one.
-The comment on the issue outlining the selection process is unprofessional and contains useless information.

2023-06-07 07:01 UTC, Aruturuu commented
New selection proccess summary

### **The team decided on using _react-hook-form_.**

There were two competitors consisting of _**Formik**_ and _**react-hook-form**_.

Leading reasons behind the choice were:
- Some members of the team tried both frameworks and found _**react-hook-form**_ to be easier to use. 
- The  _**react-hook-form**_ is more a lightweight package with no additional dependencies.
- The _**react-hook-form**_ displays better performance regarding load times and amount of re-renders.

2023-06-07 09:50 UTC, Capure approved these changes

2023-06-10 12:28 UTC, 0ZeroFive5 approved these changes
Looks good

2023-06-10 12:28 UTC, merged